(() => {
const $=s=>document.querySelector(s),sidebar=$("#sidebar"),prompt=$("#prompt"),composer=$("#composer"),conversation=$("#conversation"),welcome=$("#welcome"),suggestions=$("#suggestions"),toast=$("#toast"),fileInput=$("#file-input");
const authOverlay=$("#auth-overlay"),authForm=$("#auth-form"),authTitle=$("#auth-title"),authSwitch=$("#auth-switch"),authError=$("#auth-error"),authSubmit=authForm.querySelector(".auth-submit");
let authMode="login",currentConversation=null,attachedFiles=[],busy=false;
const showToast=m=>{toast.textContent=m;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2600)};
const resize=()=>{prompt.style.height="auto";prompt.style.height=Math.min(prompt.scrollHeight,180)+"px"};prompt.addEventListener("input",resize);
const escapeHtml=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const setBusy=v=>{busy=v;composer.querySelector(".send-button").disabled=v;composer.classList.toggle("busy",v)};
const renderMessage=(role,content)=>{const el=document.createElement("div");el.className="message "+(role==="user"?"user":"friday");el.innerHTML='<span class="label">'+(role==="user"?"You":"Friday")+"</span>"+escapeHtml(content);conversation.appendChild(el);conversation.scrollTop=conversation.scrollHeight};
const resetView=()=>{conversation.innerHTML="";conversation.classList.remove("visible");welcome.style.display="";suggestions.style.display=""};
const showConversation=()=>{welcome.style.display="none";suggestions.style.display="none";conversation.classList.add("visible")};
async function loadHistory(){const data=await FridayAPI.conversations();const h=document.querySelector(".history");h.querySelectorAll(".dynamic-history").forEach(x=>x.remove());data.conversations.forEach(c=>{const b=document.createElement("button");b.className="history-item dynamic-history";b.textContent=c.title||"Untitled conversation";b.addEventListener("click",()=>openConversation(c.id));h.appendChild(b)})}
async function openConversation(id){try{const data=await FridayAPI.messages(id);currentConversation=id;resetView();data.messages.filter(m=>m.role==="user"||m.role==="assistant").forEach(m=>renderMessage(m.role,m.content));showConversation();sidebar.classList.remove("open")}catch(e){showToast(e.message)}}
async function ensureConversation(title){if(currentConversation)return currentConversation;const d=await FridayAPI.createConversation(title.slice(0,80));currentConversation=d.conversation.id;await loadHistory();return currentConversation}
async function send(text){const value=(text??prompt.value).trim();if(!value||busy)return;showConversation();renderMessage("user",value);prompt.value="";resize();setBusy(true);try{const id=await ensureConversation(value);await FridayAPI.addMessage(id,"user",value,attachedFiles.length?{fileIds:attachedFiles.map(f=>f.id)}:undefined);const history=(await FridayAPI.messages(id)).messages.filter(m=>["system","user","assistant"].includes(m.role)).map(m=>({role:m.role,content:m.content}));const result=await FridayAPI.agent(history,{maxSteps:8});const reply=result?.result?.text||"Friday completed the request without a text response.";renderMessage("assistant",reply);await FridayAPI.addMessage(id,"assistant",reply,{provider:result?.result?.provider,model:result?.result?.model,steps:result?.result?.steps});attachedFiles=[];await loadHistory()}catch(e){renderMessage("assistant","I couldn't complete that request: "+e.message);showToast(e.message);if(e.status===401)signOut()}finally{setBusy(false)}}
async function signOut(){try{if(localStorage.getItem("friday-session-token"))await FridayAPI.logout()}catch{}localStorage.removeItem("friday-session-token");currentConversation=null;resetView();authOverlay.hidden=false}
authForm.addEventListener("submit",async e=>{e.preventDefault();authError.textContent="";authSubmit.disabled=true;const email=$("#auth-email").value.trim(),password=$("#auth-password").value;try{if(authMode==="register")await FridayAPI.register(email,password);const d=await FridayAPI.login(email,password);localStorage.setItem("friday-session-token",d.token);authOverlay.hidden=true;await loadHistory();showToast("Signed in to Friday")}catch(e){authError.textContent=e.message}finally{authSubmit.disabled=false}});
authSwitch.addEventListener("click",()=>{authMode=authMode==="login"?"register":"login";authTitle.textContent=authMode==="login"?"Sign in to Friday":"Create your Friday account";authSubmit.textContent=authMode==="login"?"Sign in":"Register";authSwitch.textContent=authMode==="login"?"Need an account? Register":"Already have an account? Sign in";$("#auth-password").autocomplete=authMode==="login"?"current-password":"new-password"});
composer.addEventListener("submit",e=>{e.preventDefault();void send()});
document.querySelectorAll("[data-prompt]").forEach(b=>b.addEventListener("click",()=>{prompt.value=b.dataset.prompt;resize();prompt.focus()}));
document.addEventListener("click",e=>{const el=e.target.closest("[data-action]");if(!el)return;const a=el.dataset.action;if(a==="toggle-sidebar")sidebar.classList.toggle("open");if(a==="new-chat"||a==="home"){currentConversation=null;attachedFiles=[];resetView();prompt.value="";resize();sidebar.classList.remove("open")}if(a==="toggle-theme"){document.body.classList.toggle("light");localStorage.setItem("friday-theme",document.body.classList.contains("light")?"light":"dark");showToast(document.body.classList.contains("light")?"Bright mode enabled":"Dark mode enabled")}if(a==="attach")fileInput.click();if(a==="voice")showToast("Voice input is reserved for the agent layer.");if(a==="model")showToast("Agent mode uses the configured backend provider.");if(a==="placeholder"&&el.getAttribute("aria-label")==="Friday settings"){const current=localStorage.getItem("friday-api-base")||"/api";const next=window.prompt("Friday backend API URL",current);if(next!==null)FridayAPI.setBase(next)}if(a==="placeholder")showToast("This Phase 1 surface is ready for the next feature.");if(a==="logout")void signOut()});
fileInput.addEventListener("change",async()=>{if(!fileInput.files.length)return;setBusy(true);try{for(const f of fileInput.files){const d=await FridayAPI.uploadFile(f);attachedFiles.push(d.file)}showToast(fileInput.files.length+" file"+(fileInput.files.length>1?"s":"")+" uploaded");fileInput.value=""}catch(e){showToast("Upload failed: "+e.message)}finally{setBusy(false)}});
document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();prompt.focus()}if(e.key==="Escape")sidebar.classList.remove("open")});
document.body.classList.toggle("light",localStorage.getItem("friday-theme")==="light");
(async()=>{try{await FridayAPI.me();authOverlay.hidden=true;await loadHistory()}catch{authOverlay.hidden=false}})();
})();